### ISSUE TITLE
Exception in segmented graph visualization

### ISSUE THREAD

**Issue by CubBossa** [CubBossa/PathFinder#16]
```
[21:29:36 INFO]: xyz issued server command: /navigate spawn
[21:29:36 WARN]: [PathFinder] Task #1487 for PathFinder v1.5.2 generated an exception
java.lang.IndexOutOfBoundsException: Index: -1, Size: 0
        at java.util.LinkedList.checkElementIndex(LinkedList.java:559) ~[?:?]
        at java.util.LinkedList.get(LinkedList.java:480) ~[?:?]
        at de.cubbossa.pathfinder.module.visualizing.FindModule.findPath(FindModule.java:136) ~[PathFinder-1.5.2.jar:?]
        at de.cubbossa.pathfinder.module.visualizing.FindModule.findPath(FindModule.java:98) ~[PathFinder-1.5.2.jar:?]
        at de.cubbossa.pathfinder.module.visualizing.command.FindCommand.lambda$new$0(FindCommand.java:23) ~[PathFinder-1.5.2.jar:?]
        at org.bukkit.craftbukkit.v1_19_R1.scheduler.CraftTask.run(CraftTask.java:101) ~[paper-1.19.2.jar:git-Paper-263]
        at org.bukkit.craftbukkit.v1_19_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:483) ~[paper-1.19.2.jar:git-Paper-263]
        at net.minecraft.server.MinecraftServer.tickChildren(MinecraftServer.java:1473) ~[paper-1.19.2.jar:git-Paper-263]
        at net.minecraft.server.dedicated.DedicatedServer.tickChildren(DedicatedServer.java:446) ~[paper-1.19.2.jar:git-Paper-263]
        at net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1397) ~[paper-1.19.2.jar:git-Paper-263]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1173) ~[paper-1.19.2.jar:git-Paper-263]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:305) ~[paper-1.19.2.jar:git-Paper-263]
        at java.lang.Thread.run(Thread.java:833) ~[?:?]
```

exception when executing /find (on a segmented graph? At least in the setup that caused the exception)

**Comment by CubBossa** [comment]
Could not reproduce
