### ISSUE TITLE
ConcurrentModificationException when deleting edges while connecting

### ISSUE THREAD

**Issue by CubBossa** [CubBossa/PathFinder#19]
When using the roadmap editor, disconnecting nodes will cause a ConcurrentModificationException if the edge tool has its first node set.

```Log
java.util.ConcurrentModificationException: null
        at java.util.ArrayList.forEach(ArrayList.java:1513) ~[?:?]
        at de.cubbossa.pathfinder.core.roadmap.RoadMap.disconnectNode(RoadMap.java:434) ~[PathFinder-2.1.0.jar:?]
        at de.cubbossa.pathfinder.core.menu.EditModeMenu.lambda$createHotbarMenu$9(EditModeMenu.java:141) ~[PathFinder-2.1.0.jar:?]
        at de.cubbossa.pathfinder.gui.inventory.AbstractMenu.handleInteract(AbstractMenu.java:368) ~[PathFinder-2.1.0.jar:?]
        at de.cubbossa.pathfinder.util.ClientNodeHandler$2.onPacketReceiving(ClientNodeHandler.java:146) ~[PathFinder-2.1.0.jar:?]
        at com.comphenix.protocol.injector.SortedPacketListenerList.invokeReceivingListener(SortedPacketListenerList.java:114) ~[ProtocolLib.jar:?]
        at com.comphenix.protocol.injector.SortedPacketListenerList.invokePacketRecieving(SortedPacketListenerList.java:67) ~[ProtocolLib.jar:?]
        at com.comphenix.protocol.injector.PacketFilterManager.postPacketToListeners(PacketFilterManager.java:549) ~[ProtocolLib.jar:?]
        at com.comphenix.protocol.injector.PacketFilterManager.invokePacketReceiving(PacketFilterManager.java:514) ~[ProtocolLib.jar:?]
        at com.comphenix.protocol.injector.netty.manager.NetworkManagerInjector.onPacketReceiving(NetworkManagerInjector.java:117) ~[ProtocolLib.jar:?]
        at com.comphenix.protocol.injector.netty.channel.NettyChannelInjector.processInboundPacket(NettyChannelInjector.java:505) ~[ProtocolLib.jar:?]
        at com.comphenix.protocol.injector.netty.channel.InboundPacketInterceptor.channelRead(InboundPacketInterceptor.java:33) ~[ProtocolLib.jar:?]
```

**Comment by CubBossa** [comment]
Actually happens whenever a node is being leftclicked = disconnect all
