### ISSUE TITLE
Cannot invoke console error

### ISSUE THREAD

**Issue by robtbs** [CubBossa/PathFinder#71]
Link: https://paste.gg/p/anonymous/9f0855545483480196e5d4cfde25e0c8

Error occurred (in the plugin loader) while disabling PathFinder v4.4.0 (Is it up to date?)
java.lang.NullPointerException: Cannot invoke "de.cubbossa.pathfinder.node.NodeHandler.cancelAllEditModes()" because the return value of "de.cubbossa.pathfinder.node.NodeHandler.getInstance()" is null
        at de.cubbossa.pathfinder.CommonPathFinder.shutdown(CommonPathFinder.java:271) ~[PathFinder-4.4.0.jar:?]
        at de.cubbossa.pathfinder.BukkitPathFinder.onDisable(BukkitPathFinder.java:142) ~[PathFinder-4.4.0.jar:?]
        at de.cubbossa.pathfinder.PathFinderPlugin.onDisable(PathFinderPlugin.java:48) ~[PathFinder-4.4.0.jar:?]
        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:283) ~[pufferfish-api-1.20.1-R0.1-SNAPSHOT.jar:?]
        at io.papermc.paper.plugin.manager.PaperPluginInstanceManager.disablePlugin(PaperPluginInstanceManager.java:224) ~[pufferfish-1.20.1.jar:git-Pufferfish-27]
        at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.disablePlugin(PaperPluginManagerImpl.java:109) ~[pufferfish-1.20.1.jar:git-Pufferfish-27]
        at org.bukkit.plugin.SimplePluginManager.disablePlugin(SimplePluginManager.java:537) ~[pufferfish-api-1.20.1-R0.1-SNAPSHOT.jar:?]
        at io.papermc.paper.plugin.manager.PaperPluginInstanceManager.enablePlugin(PaperPluginInstanceManager.java:193) ~[pufferfish-1.20.1.jar:git-Pufferfish-27]
        at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.enablePlugin(PaperPluginManagerImpl.java:104) ~[pufferfish-1.20.1.jar:git-Pufferfish-27]
        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:507) ~[pufferfish-api-1.20.1-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.craftbukkit.v1_20_R1.CraftServer.enablePlugin(CraftServer.java:642) ~[pufferfish-1.20.1.jar:git-Pufferfish-27]
        at org.bukkit.craftbukkit.v1_20_R1.CraftServer.enablePlugins(CraftServer.java:553) ~[pufferfish-1.20.1.jar:git-Pufferfish-27]
        at net.minecraft.server.MinecraftServer.loadWorld0(MinecraftServer.java:637) ~[pufferfish-1.20.1.jar:git-Pufferfish-27]
        at net.minecraft.server.MinecraftServer.loadLevel(MinecraftServer.java:436) ~[pufferfish-1.20.1.jar:git-Pufferfish-27]
        at net.minecraft.server.dedicated.DedicatedServer.initServer(DedicatedServer.java:310) ~[pufferfish-1.20.1.jar:git-Pufferfish-27]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1102) ~[pufferfish-1.20.1.jar:git-Pufferfish-27]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:319) ~[pufferfish-1.20.1.jar:git-Pufferfish-27]
        at java.lang.Thread.run(Thread.java:840) ~[?:?]

im getting this error, with 4.4.0 version and the newest version

**Comment by robtbs** [comment]
[19:06:30 WARN]: [PathFinder] Could not save styles.properties to plugins/PathFinder/lang/styles.properties because styles.properties already exists.
[19:06:30 ERROR]: Error occurred while enabling PathFinder v4.4.0 (Is it up to date?)
java.lang.NullPointerException: Cannot invoke "java.io.File.mkdirs()" because the return value of "java.io.File.getParentFile()" is null
        at de.cubbossa.pathfinder.storage.implementation.SqliteStorage.init(SqliteStorage.java:28) ~[PathFinder-4.4.0.jar:?]
        at de.cubbossa.pathfinder.storage.StorageImpl.init(StorageImpl.java:65) ~[PathFinder-4.4.0.jar:?]
        at de.cubbossa.pathfinder.CommonPathFinder.onEnable(CommonPathFinder.java:199) ~[PathFinder-4.4.0.jar:?]
        at de.cubbossa.pathfinder.BukkitPathFinder.onEnable(BukkitPathFinder.java:129) ~[PathFinder-4.4.0.jar:?]
        at de.cubbossa.pathfinder.PathFinderPlugin.onEnable(PathFinderPlugin.java:43) ~[PathFinder-4.4.0.jar:?]
        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:281) ~[pufferfish-api-1.20.1-R0.1-SNAPSHOT.jar:?]
        at io.papermc.paper.plugin.manager.PaperPluginInstanceManager.enablePlugin(PaperPluginInstanceManager.java:189) ~[pufferfish-1.20.1.jar:git-Pufferfish-27]
        at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.enablePlugin(PaperPluginManagerImpl.java:104) ~[pufferfish-1.20.1.jar:git-Pufferfish-27]
        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:507) ~[pufferfish-api-1.20.1-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.craftbukkit.v1_20_R1.CraftServer.enablePlugin(CraftServer.java:642) ~[pufferfish-1.20.1.jar:git-Pufferfish-27]
        at org.bukkit.craftbukkit.v1_20_R1.CraftServer.enablePlugins(CraftServer.java:553) ~[pufferfish-1.20.1.jar:git-Pufferfish-27]
        at net.minecraft.server.MinecraftServer.loadWorld0(MinecraftServer.java:637) ~[pufferfish-1.20.1.jar:git-Pufferfish-27]
        at net.minecraft.server.MinecraftServer.loadLevel(MinecraftServer.java:436) ~[pufferfish-1.20.1.jar:git-Pufferfish-27]
        at net.minecraft.server.dedicated.DedicatedServer.initServer(DedicatedServer.java:310) ~[pufferfish-1.20.1.jar:git-Pufferfish-27]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1102) ~[pufferfish-1.20.1.jar:git-Pufferfish-27]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:319) ~[pufferfish-1.20.1.jar:git-Pufferfish-27]
        at java.lang.Thread.run(Thread.java:840) ~[?:?]
[19:06:30 INFO]: [PathFinder] Disabling PathFinder v4.4.0

**Comment by CubBossa** [comment]
Thanks a lot for reporting, I will post a fix today :)

**Comment by CubBossa** [comment]
So I was not able to reproduce this error. Could you please run `/pf createdump` and append the according dump file from the plugin directory? It would help with fixing the issue
